# Generated by Django 4.1.3 on 2023-08-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset_data',
            fields=[
                ('asset_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('login_user', models.CharField(max_length=50)),
                ('asset_type', models.CharField(max_length=20)),
                ('Company_name', models.CharField(max_length=20)),
                ('asset_model', models.CharField(max_length=20)),
                ('serial_no', models.CharField(max_length=20)),
                ('host_name', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=10)),
                ('storage_type', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=10)),
                ('screen_size', models.CharField(max_length=20)),
                ('purchasing_date', models.CharField(max_length=20)),
                ('asset_age', models.CharField(max_length=20)),
                ('sap_code', models.CharField(max_length=20)),
                ('tba', models.CharField(max_length=20)),
                ('lt_dt_cond', models.CharField(max_length=30)),
                ('other_details', models.TextField(max_length=200)),
                ('asset_location', models.CharField(max_length=30)),
                ('asset_state', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('asset_scrap', models.CharField(max_length=20)),
            ],
        ),
    ]
