# Generated by Django 4.1.3 on 2023-08-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laptops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_data',
            name='status',
        ),
    ]
