# Generated by Django 4.1.3 on 2023-08-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptops', '0003_alter_asset_data_asset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_data',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('login_user', models.CharField(max_length=50)),
                ('alis_id', models.CharField(max_length=10, unique=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('grade', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('job_profile', models.CharField(max_length=30)),
                ('user_location', models.CharField(max_length=50)),
                ('user_state', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=30)),
                ('business_unit', models.CharField(max_length=30)),
            ],
        ),
    ]
