# Generated by Django 4.1.3 on 2023-08-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laptops', '0004_emp_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_data',
            old_name='alis_id',
            new_name='alias_id',
        ),
    ]
