# Generated by Django 4.1.3 on 2023-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptops', '0006_assign_asset_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_asset_data',
            name='assign_id',
            field=models.AutoField(auto_created=1001, primary_key=True, serialize=False),
        ),
    ]
