# Generated by Django 4.1.3 on 2023-08-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Laptops', '0007_alter_assign_asset_data_assign_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_assets_data_m',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_user', models.CharField(max_length=50)),
                ('asset_model', models.CharField(max_length=20)),
                ('serial_no', models.CharField(max_length=20)),
                ('host_name', models.CharField(max_length=20)),
                ('asset_location', models.CharField(max_length=30)),
                ('purchasing_date', models.CharField(max_length=20)),
                ('tba', models.CharField(max_length=20)),
                ('alias_id', models.CharField(max_length=10, unique=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('grade', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('asset_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Laptops.asset_data')),
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Laptops.emp_data')),
            ],
        ),
        migrations.DeleteModel(
            name='assign_asset_data',
        ),
    ]
