# Generated by Django 4.1.3 on 2023-08-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptops', '0008_assign_assets_data_m_delete_assign_asset_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_assets_data_m',
            name='assign_id',
            field=models.AutoField(auto_created=1001, primary_key=True, serialize=False),
        ),
    ]
