# Generated by Django 4.1.3 on 2023-08-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laptops', '0009_alter_assign_assets_data_m_assign_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign_assets_data_m',
            old_name='asset_id',
            new_name='asset_id1',
        ),
        migrations.RenameField(
            model_name='assign_assets_data_m',
            old_name='emp_id',
            new_name='emp_id1',
        ),
    ]
