# Generated by Django 4.1.3 on 2023-08-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptops', '0010_rename_asset_id_assign_assets_data_m_asset_id1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_data',
            name='assign_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emp_data',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
